trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\$(BuildConfiguration)\**\*MoonBankTest*.dll
      !**\obj\**
      !**\ref\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    arguments: --output $(Build.ArtifactStagingDirectory)

- task: PublishPipelineArtifact@1
  displayName: Artifact
  inputs:
      TargetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: ArtifactForMoonBank

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

#- task: ArchiveFiles@2
#  inputs:
#    rootFolderOrFile: '$(Build.BinariesDirectory)'
#    includeRootFolder: true
#    archiveType: 'zip'
#    archiveFile: 'MoonBank.zip'
#    replaceExistingArchive: true

#- task: GitHubRelease@1
#  inputs:
#    gitHubConnection: 'github.com_AxelssonOscar'
#    repositoryName: 'AxelssonOscar/MoonBank'
#    action: 'create'
#    target: '$(Build.SourceVersion)'
#    tagSource: 'userSpecifiedTag'
#    tag: 'Test 1'
#    title: 'Test 1'
#    assets: |
#      $(Build.ArtifactStagingDirectory)/*.exe
#      $(Build.ArtifactStagingDirectory)/README.txt

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'JohanOgren'
    repositoryName: 'JohanOgren/NewMoonBank'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'v1$(Release.ReleaseName)'
    assets: |
      $(Build.ArtifactStagingDirectory)/*.exe
      $(Build.ArtifactStagingDirectory)/README.txt
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'